name: Awesome function

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: Run tests with coverage
        run: |
          go test ./... -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out
          go tool cover -func=coverage.out -o coverage.txt
          echo "### Test coverage" >> "$GITHUB_STEP_SUMMARY"
          grep '^total:' coverage.txt >> "$GITHUB_STEP_SUMMARY"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.out
            coverage.txt

      - name: Send to Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          github-token: ${{ secrets.GITHUB_TOKEN }}
