name: Awesome function

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.25.x
      - run: go test ./...